In [1]:
import pandas as pd

df = pd.read_csv("Combined_dataset.csv")
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [2]:

print("Head:")
print(df.head())


print("\nTail:")
print(df.tail())


print("\nShape:")
print(df.shape)


print("\nColumns:")
print(df.columns)


print("\nData Types:")
print(df.dtypes)


print("\nSummary:")
print(df.describe(include='all'))

Head:
   product_id           title                         product_description  \
0     8376765     Lino Perros              Women Navy Blue Solid Backpack
1     9136281  Tommy Hilfiger           Unisex Navy Blue Striped Backpack
2    17633752           Lavie              Aries Women Pink Mini Backpack
3     1376949          F Gear  Unisex Navy & Grey Printed Burner Backpack
4    13939916       MYTRIDENT                    Men Blue Solid Bath Robe

   rating  ratings_count  initial_price  discount  final_price currency  \
0     3.8             15           3995      58.0  "₹3,995.00"      INR
1     4.5             67           2899      35.0  "₹2,899.00"      INR
2     4.4            226           2999      65.0  "₹2,999.00"      INR
3     4.4           1052           1675      52.0  "₹1,675.00"      INR
4     4.7             12           2899      17.0  "₹2,899.00"      INR

                                              images  ...  \
0  http://assets.myntassets.com/assets/images/837...  ...
1  http://assets.myntassets.com/assets/images/913...  ...
2  http://assets.myntassets.com/assets/images/176...  ...
3  http://assets.myntassets.com/assets/images/137...  ...
4  http://assets.myntassets.com/assets/images/pro...  ...

                                     amount_of_stars what_customers_said  \
0  {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1  {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2  {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3  {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN

  seller_name                                              sizes  \
0         NaN                               [{"size":"Onesize"}]
1         NaN                               [{"size":"Onesize"}]
2         NaN                                     [{"size":"S"}]
3         NaN                               [{"size":"Onesize"}]
4         NaN  [{"size":"M","value":"45.0in","value_name":"Fr...

                                              videos seller_information  \
0                              ["rw-8376765_cae700"]                NaN
1                              ["rw-9136281_cae700"]                NaN
2  ["https://videos.myntassets.com/assets/videos/...                NaN
3  ["https://videos.myntassets.com/assets/videos/...                NaN
4                                                NaN                NaN

                                    variations best_offer  \
0                                         [{}]         {}
1                                      [{},{}]         {}
2                          [{},{},{},{},{},{}]         {}
3                                          NaN         {}
4  [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]         {}

                                         more_offers   category
0  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4  [{"offer_name":"10% Instant Discount on IndusI...  bath-robe

[5 rows x 24 columns]

Tail:
     product_id     title                                product_description  \
995    13698258     KREDO  Men FORTE Silver Automatic Skeleton Analogue W...
996    16896006     GUESS  Women White Patterned Dial & White Straps Anal...
997     1708108  GIORDANO  Women Rose Gold-Toned Mirrored Analogue Watch ...
998    19280114  Fastrack  Men Black Brass Dial & Black Stainless Steel S...
999    18601682   BOLDFIT                           Purple Textured Yoga Mat

     rating  ratings_count  initial_price  discount   final_price currency  \
995     3.5             11          11890      50.0  "₹11,890.00"      INR
996     5.0             22           8900      45.0   "₹8,900.00"      INR
997     2.8              5           7950      50.0   "₹7,950.00"      INR
998     4.3             17           3295      20.0   "₹2,636.00"      INR
999     3.8            161            699      31.0     "₹699.00"      INR

                                                images  ...  \
995  http://assets.myntassets.com/assets/images/136...  ...
996  http://assets.myntassets.com/assets/images/168...  ...
997  http://assets.myntassets.com/assets/images/170...  ...
998  http://assets.myntassets.com/assets/images/192...  ...
999  http://assets.myntassets.com/assets/images/186...  ...

                                       amount_of_stars what_customers_said  \
995  {"1_star":3,"2_stars":0,"3_stars":2,"4_stars":...                 NaN
996  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
997  {"1_star":2,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
998  {"1_star":1,"2_stars":2,"3_stars":0,"4_stars":...                 NaN
999  {"1_star":24,"2_stars":8,"3_stars":22,"4_stars...                 NaN

        seller_name                 sizes  \
995             NaN  [{"size":"Onesize"}]
996             NaN  [{"size":"Onesize"}]
997             NaN  [{"size":"Onesize"}]
998  Tru███m R███il  [{"size":"Onesize"}]
999             NaN   [{"size":"Medium"}]

                                                videos  \
995                                    ["pi-13698258"]
996  ["rw-16896006_cae700","https://videos.myntasse...
997                                                NaN
998                                                NaN
999                                                NaN

                                    seller_information  \
995                                                NaN
996                                                NaN
997                                                NaN
998  Sho███o. ███-10█████████enu███████████████████...
999                                                NaN

                    variations  \
995                        NaN
996                        NaN
997  [{},{},{},{},{},{},{},{}]
998                        NaN
999              [{},{},{},{}]

                                            best_offer  \
995                                                 {}
996                                                 {}
997                                                 {}
998  {"applicable_on":"Orders above Rs. 1499 (only ...
999                                                 {}

                                           more_offers   category
995  [{"offer_name":"10% Instant Discount on Citi C...    watches
996  [{"offer_name":"10% Instant Discount on Citi C...    watches
997  [{"offer_name":"10% Instant Discount on Citi C...    watches
998  [{"offer_name":"10% Instant Discount on IndusI...    watches
999  [{"offer_name":"10% Instant Discount on Citi C...  yoga-mats

[5 rows x 24 columns]

Shape:
(1000, 24)

Columns:
Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

Data Types:
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

Summary:
          product_id     title   product_description     rating  \
count   1.000000e+03      1000                  1000  1000.0000
unique           NaN       454                   989        NaN
top              NaN  Roadster  Women Pink Solid Top        NaN
freq             NaN        30                     3        NaN
mean    1.713437e+07       NaN                   NaN     3.6215
std     3.813766e+06       NaN                   NaN     1.3744
min     5.868460e+05       NaN                   NaN     0.0000
25%     1.511501e+07       NaN                   NaN     3.7000
50%     1.820890e+07       NaN                   NaN     4.1000
75%     1.902737e+07       NaN                   NaN     4.3000
max     2.274707e+07       NaN                   NaN     5.0000

        ratings_count  initial_price    discount final_price currency  \
count     1000.000000     1000.00000  879.000000        1000     1000
unique            NaN            NaN         NaN         466        1
top               NaN            NaN         NaN   "₹999.00"      INR
freq              NaN            NaN         NaN          25     1000
mean        76.691000     2723.24100   53.503982         NaN      NaN
std        241.114263     2408.69736   18.029201         NaN      NaN
min          0.000000      249.00000    1.000000         NaN      NaN
25%          7.000000     1399.00000   44.000000         NaN      NaN
50%         17.000000     1999.00000   56.000000         NaN      NaN
75%         58.000000     3299.00000   66.000000         NaN      NaN
max       4441.000000    22199.00000   88.000000         NaN      NaN

                                                   images  ...  \
count                                                1000  ...
unique                                               1000  ...
top     http://assets.myntassets.com/assets/images/186...  ...
freq                                                    1  ...
mean                                                  NaN  ...
std                                                   NaN  ...
min                                                   NaN  ...
25%                                                   NaN  ...
50%                                                   NaN  ...
75%                                                   NaN  ...
max                                                   NaN  ...

                                          amount_of_stars  \
count                                                1000
unique                                                808
top     {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...
freq                                                  114
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

                                      what_customers_said   seller_name  \
count                                                 427           699
unique                                                302           301
top     [{"percentage":"100","value_name":"Fit, Just R...  Sup███om ███
freq                                                   27            40
mean                                                  NaN           NaN
std                                                   NaN           NaN
min                                                   NaN           NaN
25%                                                   NaN           NaN
50%                                                   NaN           NaN
75%                                                   NaN           NaN
max                                                   NaN           NaN

                       sizes                 videos  \
count                   1000                    219
unique                   672                    219
top     [{"size":"Onesize"}]  ["rw-8376765_cae700"]
freq                     135                      1
mean                     NaN                    NaN
std                      NaN                    NaN
min                      NaN                    NaN
25%                      NaN                    NaN
50%                      NaN                    NaN
75%                      NaN                    NaN
max                      NaN                    NaN

                                       seller_information variations  \
count                                                 699        438
unique                                                298         22
top     Plo███o- ███ 1s█████████Sui███████████████████...       [{}]
freq                                                   40        126
mean                                                  NaN        NaN
std                                                   NaN        NaN
min                                                   NaN        NaN
25%                                                   NaN        NaN
50%                                                   NaN        NaN
75%                                                   NaN        NaN
max                                                   NaN        NaN

       best_offer                                        more_offers category
count        1000                                               1000     1000
unique        468                                                159       97
top            {}  [{"offer_name":"10% Instant Discount on IndusI...     tops
freq          306                                                265      122
mean          NaN                                                NaN      NaN
std           NaN                                                NaN      NaN
min           NaN                                                NaN      NaN
25%           NaN                                                NaN      NaN
50%           NaN                                                NaN      NaN
75%           NaN                                                NaN      NaN
max           NaN                                                NaN      NaN

[11 rows x 24 columns]

In [3]:

print("Missing Values:")
print(df.isnull().sum())

Missing Values:
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [4]:
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numerical_cols:
    df[col] = df[col].fillna(df[col].mean())

In [5]:
categorical_cols = df.select_dtypes(include=['object']).columns

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [6]:
print(df.isnull().sum())

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [7]:
print(df.columns.tolist())

['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [8]:
selected_data = df[['product_id','title', 'category', 'final_price']]
selected_data.head()

   product_id           title   category  final_price
0     8376765     Lino Perros  backpacks  "₹3,995.00"
1     9136281  Tommy Hilfiger  backpacks  "₹2,899.00"
2    17633752           Lavie  backpacks  "₹2,999.00"
3     1376949          F Gear  backpacks  "₹1,675.00"
4    13939916       MYTRIDENT  bath-robe  "₹2,899.00"

In [9]:
print(df['final_price'].dtype)
print(df['final_price'].head())

object
0    "₹3,995.00"
1    "₹2,899.00"
2    "₹2,999.00"
3    "₹1,675.00"
4    "₹2,899.00"
Name: final_price, dtype: object

In [10]:
df['final_price'] = (
    df['final_price']
    .astype(str)
    .str.replace('"', '', regex=False)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
)

df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

print(df['final_price'].head())
print(df['final_price'].dtype)

0    3995.0
1    2899.0
2    2999.0
3    1675.0
4    2899.0
Name: final_price, dtype: float64
float64

In [11]:
filtered_data = df[df['final_price'] > 1000]

filtered_data.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [12]:
print("Before:", df.shape)

df.drop_duplicates(inplace=True)

print("After:", df.shape)

Before: (1000, 24)
After: (1000, 24)

In [13]:
df['quantity'] = 1

df['total_amount'] = df['final_price'] * df['quantity']

df[['title', 'final_price', 'quantity', 'total_amount']].head()

            title  final_price  quantity  total_amount
0     Lino Perros       3995.0         1        3995.0
1  Tommy Hilfiger       2899.0         1        2899.0
2           Lavie       2999.0         1        2999.0
3          F Gear       1675.0         1        1675.0
4       MYTRIDENT       2899.0         1        2899.0

In [14]:
df.to_csv("cleaned_shopping_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Summary

This project demonstrates basic data exploration and cleaning using Pandas.

Tasks performed:
- Loaded Combined_dataset.csv into a Pandas DataFrame.
- Explored the dataset using head(), tail(), shape, columns, and data types.
- Identified and handled missing values.
- Selected relevant columns and filtered records.
- Removed duplicate entries.
- Created a derived column named total_amount.
- Saved the cleaned dataset as cleaned_dataset.csv.

Tools Used:
- Python
- Pandas